[application]
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "ferlora"

[web.watcher]
rebuild_html = true
watch_path = [
  "src",
  "assets",
  "input.css",
  "Dioxus.toml"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# [[web.proxy]]
# backend = "http://localhost:8000/api/"
