[package]
name = "ferlory_main"
version = "0.1.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2024"

[dependencies]
dioxus = { workspace = true }
ferlory_routes = { path = "../routes" }
ferlory_components = { path = "../components" }
ferlory_utils = { path = "../utils" }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
