[package]
name = "ferlory_main"
version = "0.1.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.6.3", features = ["fullstack", "router"] }
ferlory_routes = { path = "../routes" }
ferlory_components = { path = "../components" }
ferlory_utils = { path = "../utils" }

[build-dependencies]
walkdir = "2.5.0"
phf = { version = "0.11", features = ["macros"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
