[package]
name = "ferlory_components"
version = "0.1.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2024"

[dependencies]
dioxus = { workspace = true }
gloo = { workspace = true }
generated_typst = { path = "../generated_typst" }
slug = "0.1.6"
rand = "0.9"
getrandom = { version = "0.3", features = ["wasm_js"]}
# reqwest = "0.12.12"
# dioxus-typst = { path = "../dioxus-typst" }
# typst = "0.13.0"
# tokio = "1.44.1"
