[package]
name = "ferlory_utils"
version = "0.1.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2024"

[dependencies]
dioxus = { workspace = true }
gloo = { workspace = true }
ferlory_components = { path = "../components" }
