[package]
name = "ferlory_routes"
version = "0.1.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2024"

[dependencies]
dioxus = { workspace = true }
ferlory_macros = { path = "../macros" }
ferlory_components = { path = "../components" }
ferlory_utils= { path = "../utils" }
rand = "0.9"
getrandom = { version = "0.3", features = ["wasm_js"]}
